namespace: sirocco-operator-system
namePrefix: sirocco-operator-
labels:
- includeSelectors: true
  pairs:
    operator: sirocco-operator
resources:
- operator-role.yaml
- operator-role-binding.yaml
- deployment.yaml
- testruns_sirocco_dev.yaml
- namespace.yaml
images:
- name: operator
  newName: sirocco-operator
  newTag: local
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization